### ISSUE TITLE
delete does not delete until of_changed() is called...

### ISSUE THREAD

**Issue by michelos75** [informaticon/inc.win.base.pb-json#1]
Hi!
When I delete a node (using of_delete_node) and request the JSON string from a parent node, the deleted nodes are still inside the JSON result.

I solved this problem by calling this.of_changed() before return.

Maybe you should include this in a future release, or maybe I understood something wrong!!!

**Comment by steppenwolfXYZ** [comment]
Thanks a lot for that hint, just fixed it.
