### ISSUE TITLE
could help me with example parsing json multi parent and multi child 

### ISSUE THREAD

**Issue by Egymind** [informaticon/inc.win.base.pb-json#2]
if you could help i need to parse this json with multi parent and multi child 
[
  {
    "hashed_id": "had1568",
    "retailer_number": "01062165935",
    "order_details": [
      {
        "Item": "110",
        "quantity": 12.00,
        "price": 55.5,
        "tax": 0.00
      },
      {
        "Item": "120",
        "quantity": 17.00,
        "price": 55.5,
        "tax": 0.00
      },
      {
        "Item": "130",
        "quantity": 13.5,
        "price": 50.0,
        "tax": 0.00
      }
    ]
  },
  {
    "hashed_id": "1536AQ",
    "retailer_number": "01016696690",
    "order_details": [
      {
        "Item": "140",
        "quantity": 12.00,
        "price": 55.5,
        "tax": 0.00
      },
      {
        "Item": "150",
        "quantity": 17.00,
        "price": 55.5,
        "tax": 0.00
      },
      {
        "Item": "160",
        "quantity": 13.5,
        "price": 50.0,
        "tax": 0.00
      }
    ]
  }
]

**Comment by simcrack** [comment]
What is your problem with parsing this?

**Comment by simcrack** [comment]
Closed due to inactivity.
